# Generated by Django 3.2.8 on 2021-10-05 20:45

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(null=True, upload_to=music.models.Song.song_directory_path),
        ),
    ]
